name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run check-format
      - run: npm run lint
      - run: npm run test:once
